name: typeCheck

on:
  pull_request

permissions:
  contents: read

env:
  POSTGRES_PRISMA_URL: postgresql://postgres:postgres@localhost:5432/postgres # Example connection string for a local Postgres instance

jobs:
  typeCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4.2.1
      - run: yarn install --immutable
      - run: yarn db:generate
      - run: yarn typeCheck
